version: "3"
# name: minecraft-server
services:


  mc:
    container_name: minecraft-server-$SERVER_NAME
    image: itzg/minecraft-server:2023.8.2
    restart: always
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      SEED: $SEED
      DIFFICULTY: $DIFFICULTY
      SERVER_NAME: "Self Hosted Server"
      MOTD: "Server running on container"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "4G"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      GENERATE_STRUCTURES: true
      ALLOW_NETHER: true
      VERSION: $MC_VERSION
      FABRIC_LAUNCHER_VERSION: $FABRIC_LAUNCHER_VERSION
      FABRIC_LOADER_VERSION: $FABRIC_LOADER_VERSION
      ICON: "https://b.thumbs.redditmedia.com/Flac-ySmslzY0SE583PNA42rFbcYxLt7hqgCeUrC11s.png"
      UID: $PUID
      GID: $GID
    tty: true
    stdin_open: true
    volumes:
      - $MOUNT_POINT_GAMES/Minecraft/$MAJOR_VERSION/$SERVER_NAME/config:/data
      - $MOUNT_POINT_GAMES/Minecraft/$MAJOR_VERSION/$SERVER_NAME/mods:/data/mods
    labels:
      # HOMEPAGE
      - homepage.group=Tools
      - homepage.name=MC Vanilla ++
      - homepage.icon=minecraft.png
      - homepage.description=Minecraft vanilla with QOL mods
      - homepage.widget.type=minecraft
      - homepage.widget.url=udp://$MC_IP:$MC_PORT
      