sonarr:
  server:
    address: http://sonarr
    port: 8989
  
  config:
    host:
      analyticsEnabled: false
    ui:
      firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
      timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
      uiLanguage: 1
    naming:
      renameEpisodes: true
      replaceIllegalCharacters: true
      standardEpisodeFormat: "{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Full}"
      animeEpisodeFormat: "{Series Title} - S{season:00}E{episode:00} - {Quality Full}"
      seriesFolderFormat: "{Series Title}"
      seasonFolderFormat: "Saison {season}"
    mediamanagement:
      copyUsingHardlinks: true
      deleteEmptyFolders: true
      rescanAfterRefresh: always
      downloadPropersAndRepacks: preferAndUpgrade

  rootfolder:
    - name: tv
      path: /data/media/tv
    - name: animes
      path: /data/media/animes
      
  downloadclient:
    - name: Deluge
      enable: true
      protocol: torrent
      fields:
        - name: host
          value: http://deluge
        - name: port
          value: 8112
        - name: password
          value: deluge
      implementation: Deluge
      configContract: DelugeSettings


radarr:
  server:
    address: http://radarr
    port: 7878
  
  config:
    host:
      analyticsEnabled: false
    ui:
      firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
      timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
      uiLanguage: 1 # 1 = English, 2 = French, 3 = Spanish...
      movieInfoLanguage: 2
    naming:
      renameMovies: true
      replaceIllegalCharacters: true
      colonReplacementFormat: spaceDashSpace
      # https://trash-guides.info/Radarr/Radarr-recommended-naming-scheme/
      standardMovieFormat: "{Movie CleanTitle} {(Release Year)}"
      movieFolderFormat: "{Movie CleanTitle} ({Release Year})"
      includeQuality: false
      replaceSpaces: false
    mediamanagement:
      copyUsingHardlinks: true
      deleteEmptyFolders: true
      rescanAfterRefresh: always
      downloadPropersAndRepacks: preferAndUpgrade
  
  rootfolder:
    - name: Movies
      path: /data/media/films

  downloadclient:
    - name: Deluge
      enable: true
      protocol: torrent
      fields:
        - name: host
          value: http://deluge
        - name: port
          value: 8112
        - name: password
          value: deluge
      implementation: Deluge
      configContract: DelugeSettings


prowlarr:
  server:
    address: http://prowlarr
    port: 9696
  
  config:
    host:
      analyticsEnabled: false
    ui:
      theme: dark
  
  downloadclient:
    - name: Deluge
      enable: true
      protocol: torrent
      fields:
        - name: host
          value: http://deluge
        - name: port
          value: 8112
        - name: password
          value: deluge
      implementation: Deluge
      configContract: DelugeSettings
      