services:

  code-server:
    image: lscr.io/linuxserver/code-server:4.103.2
    container_name: code-server
    restart: unless-stopped
    # networks:
    #   - proxy
    #ports:
    #  - 8443:8443
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ${MOUNT_POINT_DATA}/code-server:/config
    labels:
      # HOMEPAGE
      - homepage.group=Tools
      - homepage.name=Code-Server
      - homepage.icon=code.png
      - homepage.href=https://code-server.${DOMAIN_NAME}
      # TRAEFIK
      # - traefik.enable=true
      # - traefik.docker.network=proxy
      # - traefik.http.routers.code-server.rule=Host(`code-server.${DOMAIN_NAME}`)
      # - traefik.http.services.code-server.loadbalancer.server.port=8443
      # GODOXY
      - port.proxy=8443


  semaphore-db:
    image: mysql:8.1
    container_name: semaphore-db
    hostname: mysql
    restart: unless-stopped
    # networks:
    #   - proxy
    # ports:
    #   - 3306:3306
    volumes:
      - ${MOUNT_POINT_DATA}/semaphore/db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: ${DB_PASSWORD}

  semaphore-server:
    image: semaphoreui/semaphore:v2.16.28
    container_name: semaphore
    restart: unless-stopped
    # networks:
    #   - proxy
    #ports:
    #  - 3000:3000
    user: "${PUID}:${PGID}"
    depends_on:
      - semaphore-db
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${DB_PASSWORD}
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_PASSWORD}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: ${SEMAPHORE_USER}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_KEY_ENCRYPTION}
      ANSIBLE_HOST_KEY_CHECKING: false  # (optional) change to true if you want to enable host key checking
    volumes:
      - ${MOUNT_POINT_DATA}/semaphore/inventory:/inventory:ro
      - ${MOUNT_POINT_DATA}/semaphore/authorized-keys:/authorized-keys:ro
      - ${MOUNT_POINT_DATA}/semaphore/config:/etc/semaphore:rw
    labels:
      # HOMEPAGE
      - homepage.group=Tools
      - homepage.name=Semaphore
      - homepage.icon=ansible.png
      - homepage.href=https://semaphore.${DOMAIN_NAME}
      # TRAEFIK
      # - traefik.enable=true
      # - traefik.docker.network=proxy
      # - traefik.http.routers.semaphore.rule=Host(`semaphore.${DOMAIN_NAME}`)
      # - traefik.http.services.semaphore.loadbalancer.server.port=3000
      # GODOXY
      - proxy.port=3000

# networks:
#   proxy:
#     external: true
