version: '3'
services:

  traefik:
    image: traefik:v3.4.3
    container_name: traefik
    restart: always
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $MOUNT_POINT_DATA/traefik/traefik.yml:/etc/traefik/traefik.yml
      - $MOUNT_POINT_DATA/traefik/traefik-dynamic.yml:/etc/traefik/traefik-dynamic.yml
      - $MOUNT_POINT_DATA/traefik/certs:/etc/traefik/certs:ro
    labels:
      # HOMEPAGE
      - homepage.group=Networking
      - homepage.name=Traefik
      - homepage.icon=traefik.png
      - homepage.href=https://traefik.$DOMAIN_NAME
      - homepage.ping=https://traefik.$DOMAIN_NAME
      - homepage.description=Reverse proxy
      - homepage.widget.type=traefik
      - homepage.widget.url=https://traefik.$DOMAIN_NAME
      # TRAEFIK
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.traefik.rule=Host(`traefik.$DOMAIN_NAME`)
      - traefik.http.routers.traefik.service=api@internal
    extra_hosts: 
        - host.docker.internal:172.17.0.1

networks:
  proxy:
    external: true
